# Generated by Django 2.1.2 on 2018-11-18 07:50

import bbc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=1)),
                ('vip', models.CharField(default=0, max_length=1)),
                ('integral', models.IntegerField(default=0)),
                ('portrait', models.ImageField(upload_to=bbc.models.user_upload_to)),
            ],
        ),
    ]
