# Generated by Django 2.1.2 on 2018-11-27 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=20)),
                ('news_sort', models.CharField(max_length=4)),
                ('news_source', models.CharField(max_length=50)),
                ('news_center', models.CharField(max_length=100)),
                ('news_portrait', models.ImageField(upload_to='')),
                ('news_content', models.CharField(max_length=50)),
                ('news_check', models.CharField(choices=[('0', '正在审核'), ('1', '审核通过'), ('-1', '审核失败')], default=0, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NumberUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pays', models.CharField(max_length=10)),
                ('money', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays_number', models.CharField(max_length=20, unique=True)),
                ('pays_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pays_money', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='neck_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pays',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbc.Users'),
        ),
        migrations.AddField(
            model_name='numberuser',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbc.Users'),
        ),
        migrations.AddField(
            model_name='news',
            name='news_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbc.Users'),
        ),
    ]
