# Generated by Django 2.1.2 on 2018-11-28 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0003_auto_20181128_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_look',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='news_share',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='news_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='numberuser',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
