# Generated by Django 2.1.2 on 2018-11-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0004_auto_20181128_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.CharField(max_length=500),
        ),
    ]
