# Generated by Django 2.1.2 on 2018-11-29 03:26

import bbc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0005_auto_20181129_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_portrait',
            field=models.ImageField(upload_to=bbc.models.user_upload_to),
        ),
        migrations.AlterField(
            model_name='users',
            name='portrait',
            field=models.ImageField(upload_to=bbc.models.news_upload_to),
        ),
    ]
