# Generated by Django 2.1.2 on 2018-11-29 03:54

import bbc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0006_auto_20181129_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_author',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_portrait',
            field=models.ImageField(upload_to=bbc.models.news_upload_to),
        ),
    ]
