# Generated by Django 2.1.2 on 2018-11-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0007_auto_20181129_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_check',
            field=models.CharField(choices=[('0', '正在审核'), ('1', '审核通过'), ('-1', '审核失败')], default=0, max_length=2),
        ),
    ]
