# Generated by Django 2.1.2 on 2018-12-05 12:26

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbc', '0012_comments_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='富文本新闻内容'),
        ),
    ]
