# Generated by Django 2.1.2 on 2018-10-30 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_entry_test_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
